### ISSUE TITLE
sed: couldn't open temporary file /fuseki-base/configuration/sedG8TZFR

### ISSUE THREAD

**Issue by faubulous** [SemanticComputing/fuseki-docker#12] opened 2022-08-04 08:52 UTC
Hello everyone,

I am trying to set up a Fuseki instance using Docker with support for adding new datasets through the UI. I followed your instructions as close as possible:

1. Cloned repo
2. Built docker image (including the chgrp command)
3. Created a local data and config directory with local user privileges
4. Copied assembler.ttl into the config directory

Now when I run the command:

`docker run --rm -it -p 3030:3030 --name fuseki -e ADMIN_PASSWORD=mypassword -e ENABLE_DATA_WRITE=true -e ENABLE_UPDATE=true -e ENABLE_UPLOAD=true -e QUERY_TIMEOUT=120000 --mount type=bind,source=/my/fuseki-data,target=/fuseki-base/databases --mount type=bind,source=/my/fuseki-configuration,target=/fuseki-base/configuration secoresearch/fuseki`

I checked that all the variables were replaced and that the absolute path to the config and data directory are correct. Then I get the following error:

`sed: couldn't open temporary file /fuseki-base/configuration/sedG8TZFR: Permission denied`
`sed: couldn't open temporary file /fuseki-base/configuration/sedbtSYlW: Permission denied`

What am I doing wrong?

**Comment by faubulous** [comment] 2022-08-04 09:47
I forgot to mention that I am on Fedora Linux 36.

It seems to be an issue with mounting the volumes from my user directory because the same command with a explicitly created docker volume runs just fine.

**Comment by faubulous** [comment] 2022-08-04 10:13
However, even with the explicitly created volumes I cannot add any data to the store. When I upload files everything seems to go smooth, however, no data gets actually added to the store. All graphs remain empty.

**Comment by mosoriob** [comment] 2022-11-16 19:31
I'm creating the dataset using the REST API

```console
       curl -v 'http://localhost:3030/$/datasets' \
          -X POST \ 
          -u admin:${ADMIN_PASSWORD} \ 
          --data-raw "dbName=newDataSet&dbType=tdb2
```

**Comment by yoge1** [comment] 2023-01-19 15:33
Sorry about a very slow response! I tested your workflow (with the current fuseki-docker version 4.7.0).

Bind mount: For me, this works (macOS 12.6.2). I you might have an issue related to directory write permissions of the user the docker container is run as. 

Volume: For me, this works. Did you upload the data to a named graph or the default graph? With the default assembler.ttl, you should only upload to a named graph, as the default graph is the union of the named graphs (however, you can access data uploaded directly to default graph using a special graph name <urn:x-arq:DefaultGraph>).

**Comment by yoge1** [comment] 2023-01-31 14:44
I'm closing the issue, please re-open if necessary.

**Closed by yoge1** 2023-01-31 14:44 UTC

**Comment by yoge1** [comment] 2023-09-07 17:09
The cause for the error `sed: couldn't open temporary file /fuseki-base/configuration/seduXVqzT: Permission denied` seems to be related to file permissions (I have now encountered this in some environments).

A workaround is to to run the container as the root user, or to give write permissions to the host directory `/my/fuseki-configuration` (seems to work on Ubuntu Linux, but not on Mac). Other possibility is to use a volume instead of a bind mount for `/fuseki-base/configuration` (as you found out).

As it's perhaps slightly incongruent to both have an (explicit) `assembler.ttl` file in use and use environment variables to enable endpoints (as the environment variables cause modifications to the `assembler.ttl` file), I now added a note on this in README, saying that it is not encouraged to have/use them both. Instead, it is recommended to enable the endpoints by editing the file `assembler.ttl` acordingly.
